### ISSUE TITLE
Enabler: Set up integration tests

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/bestbets-api#39]
# Set up integration tests

Integration tests are needed in order to automatically detect regressions when the code is changed.

> **ESTIMATE** 20

### Sub-Tasks
- [x] Create a docker-compose stack with containers for the API and Elasticsearch.   Issue #40 
- [x] Add submodule to reference http://github.com/nciocpl/bestbets-loader
- [x] In `load-integration-data.sh`
   - [x] Fetch the submodule (`git submodule init && git submodule update`)
   - [x] Override the configuration to load bestbets-content from a fixed commit instead of the current tip of `master`.
     - `NODE_CONFIG='{ "pipeline": { "source": { "config": { "resourcesPath": "/tree/0032561df90ba71f4c19e955bcfc1ddb6cab8b85/content" } } } }'`
- [x] Port existing karate features to run in the new system.
- [ ] Update GH actions workflow to run integration tests as part of a pull request.
